In [5]:
!pip install https://github.com/druzsan/justetf-scraping/archive/refs/heads/main.zip

Collecting https://github.com/druzsan/justetf-scraping/archive/refs/heads/main.zip
  Using cached https://github.com/druzsan/justetf-scraping/archive/refs/heads/main.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.0.0 in c:\users\navon\anaconda3\lib\site-packages (from justetf-scraping==0.1.0) (4.12.3)
Requirement already satisfied: pandas>=2.0.0 in c:\users\navon\anaconda3\lib\site-packages (from justetf-scraping==0.1.0) (3.0.2)
Requirement already satisfied: pycountry in c:\users\navon\anaconda3\lib\site-packages (from justetf-scraping==0.1.0) (26.2.16)
Requirement already satisfied: requests>=2.0.0 in c:\users\navon\anaconda3\lib\site-packages (from justetf-scraping==0.1.0) (2.32.3)
Requirement already satisfied: websocket-client in c:\users\navon\anaconda3\lib\site-packages (from justetf-scraping==0.1.0) (1.8.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\navon\anaconda3\lib\site-packages (from beautifulsoup4>=4.0.0->justetf-scraping==0.1.0) (2.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\navon\anaconda3\lib\site-packages (from pandas>=2.0.0->justetf-scraping==0.1.0) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\navon\anaconda3\lib\site-packages (from pandas>=2.0.0->justetf-scraping==0.1.0) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\navon\anaconda3\lib\site-packages (from pandas>=2.0.0->justetf-scraping==0.1.0) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\navon\anaconda3\lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\navon\anaconda3\lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navon\anaconda3\lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navon\anaconda3\lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (2026.7.22)
Requirement already satisfied: six>=1.5 in c:\users\navon\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->justetf-scraping==0.1.0) (1.16.0)

In [6]:
import sys
print("Kernel's Python:", sys.executable)

Kernel's Python: C:\Users\navon\anaconda3\envs\quant\python.exe

In [7]:
import sys
!{sys.executable} -m pip install https://github.com/druzsan/justetf-scraping/archive/refs/heads/main.zip

Collecting https://github.com/druzsan/justetf-scraping/archive/refs/heads/main.zip
  Using cached https://github.com/druzsan/justetf-scraping/archive/refs/heads/main.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.0.0 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from justetf-scraping==0.1.0) (4.14.3)
Requirement already satisfied: pandas>=2.0.0 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from justetf-scraping==0.1.0) (3.0.2)
Collecting pycountry (from justetf-scraping==0.1.0)
  Using cached pycountry-26.2.16-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests>=2.0.0 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from justetf-scraping==0.1.0) (2.33.1)
Requirement already satisfied: websocket-client in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from justetf-scraping==0.1.0) (1.8.0)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from beautifulsoup4>=4.0.0->justetf-scraping==0.1.0) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from beautifulsoup4>=4.0.0->justetf-scraping==0.1.0) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from pandas>=2.0.0->justetf-scraping==0.1.0) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from pandas>=2.0.0->justetf-scraping==0.1.0) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from pandas>=2.0.0->justetf-scraping==0.1.0) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->justetf-scraping==0.1.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\navon\anaconda3\envs\quant\Lib\site-packages (from requests>=2.0.0->justetf-scraping==0.1.0) (2026.2.25)
Using cached pycountry-26.2.16-py3-none-any.whl (8.0 MB)
Building wheels for collected packages: justetf-scraping
  Building wheel for justetf-scraping (pyproject.toml): started
  Building wheel for justetf-scraping (pyproject.toml): finished with status 'done'
  Created wheel for justetf-scraping: filename=justetf_scraping-0.1.0-py3-none-any.whl size=21819 sha256=eaf7ed37d8560e4e6554fab22d4e758f36b9fec67a18b83ebda3e005c6a23915
  Stored in directory: C:\Users\navon\AppData\Local\Temp\pip-ephem-wheel-cache-_suaitck\wheels\7c\5b\21\5057fa30f32768e8717f5e65da357497de11cf7fddbb76969d
Successfully built justetf-scraping
Installing collected packages: pycountry, justetf-scraping

   ---------------------------------------- 0/2 [pycountry]
   ---------------------------------------- 0/2 [pycountry]
   ---------------------------------------- 0/2 [pycountry]
   ---------------------------------------- 0/2 [pycountry]
   ---------------------------------------- 0/2 [pycountry]
   ---------------------------------------- 0/2 [pycountry]
   ---------------------------------------- 0/2 [pycountry]
   ---------------------------------------- 2/2 [justetf-scraping]

Successfully installed justetf-scraping-0.1.0 pycountry-26.2.16

In [1]:
import justetf_scraping
df = justetf_scraping.load_overview(strategy="epg-longOnly")
print(f"Total long-only funds: {len(df)}")
print(list(df.columns))
df.head(10)

Total long-only funds: 3770
['wkn', 'ticker', 'valor', 'name', 'inception_date', 'age_in_days', 'age_in_years', 'strategy', 'domicile_country', 'currency', 'hedged', 'securities_lending', 'dividends', 'ter', 'replication', 'size', 'is_sustainable', 'number_of_holdings', 'yesterday', 'last_week', 'last_month', 'last_three_months', 'last_six_months', 'last_year', 'last_three_years', 'last_five_years', '2025', '2024', '2023', '2022', 'last_dividends', 'last_year_dividends', 'last_year_volatility', 'last_three_years_volatility', 'last_five_years_volatility', 'last_year_return_per_risk', 'last_three_years_return_per_risk', 'last_five_years_return_per_risk', 'max_drawdown', 'last_year_max_drawdown', 'last_three_years_max_drawdown', 'last_five_years_max_drawdown']

,wkn,ticker,valor,name,inception_date,age_in_days,age_in_years,strategy,domicile_country,currency,...,last_year_volatility,last_three_years_volatility,last_five_years_volatility,last_year_return_per_risk,last_three_years_return_per_risk,last_five_years_return_per_risk,max_drawdown,last_year_max_drawdown,last_three_years_max_drawdown,last_five_years_max_drawdown
isin,,,,,,,,,,,,,,,,,,,,,
IE00B5BMR087,A0YEDG,SXR8,10737041,iShares Core S&P 500 UCITS ETF USD (Acc),2010-05-19,5984,16.394521,Long-only,Ireland,USD,...,12.46,15.48,17.49,1.77,1.35,0.82,-33.71,-7.49,-22.60,-22.60
IE00B4L5Y983,A0RPWH,EUNL,10608388,iShares Core MSCI World UCITS ETF USD (Acc),2009-09-25,6220,17.041096,Long-only,Ireland,USD,...,10.75,12.95,14.69,1.94,1.53,0.87,-33.91,-6.47,-20.45,-20.45
IE00BK5BQT80,A2PKXG,VWCE,48616202,Vanguard FTSE All-World UCITS ETF (USD) Accumu...,2019-07-23,2632,7.210959,Long-only,Ireland,USD,...,10.37,12.28,13.67,2.16,1.64,0.92,-33.48,-6.92,-19.59,-19.59
IE00B3XXRP09,A1JX53,VUSA,18575508,Vanguard S&P 500 UCITS ETF (USD) Distributing,2012-05-22,5250,14.383562,Long-only,Ireland,USD,...,12.68,15.86,17.75,1.74,1.31,0.81,-33.70,-7.49,-23.75,-23.75
IE00BKM4GZ66,A111X9,IS3N,24209517,iShares Core MSCI Emerging Markets IMI UCITS E...,2014-05-30,4512,12.361644,Long-only,Ireland,USD,...,20.69,16.47,15.88,1.64,1.36,0.65,-34.34,-13.05,-17.67,-22.30
IE00B3YCGJ38,A1CYW7,P500,11358996,Invesco S&P 500 UCITS ETF,2010-05-20,5983,16.391781,Long-only,Ireland,USD,...,12.63,15.60,17.59,1.75,1.35,0.83,-33.62,-7.54,-22.61,-22.61
IE00B4ND3602,A1KWPQ,PPFB,12881542,iShares Physical Gold ETC,2011-04-08,5660,15.506849,Long-only,Ireland,USD,...,25.32,19.12,17.46,0.45,1.50,1.11,-37.20,-23.37,-23.37,-23.37
IE00BFMXXD54,A2PFN2,VUAA,46931424,Vanguard S&P 500 UCITS ETF (USD) Accumulating,2019-05-14,2702,7.402740,Long-only,Ireland,USD,...,12.74,15.82,17.70,1.73,1.32,0.81,-33.70,-7.48,-23.74,-23.74
IE00B6R52259,A1JMDF,IUSQ,14137311,iShares MSCI All Country World UCITS ETF USD (...,2011-10-21,5464,14.969863,Long-only,Ireland,USD,...,10.45,12.31,13.82,2.16,1.64,0.91,-33.59,-6.90,-19.93,-19.93
IE00B53SZB19,A0YEDL,SXRV,10737617,iShares Nasdaq 100 UCITS ETF (Acc),2010-01-26,6097,16.704110,Long-only,Ireland,USD,...,19.09,20.52,23.19,1.63,1.26,0.75,-31.43,-11.27,-26.49,-31.43

In [2]:
import justetf_scraping
print([x for x in dir(justetf_scraping) if not x.startswith("_")])
help(justetf_scraping.load_overview)

['charts', 'compare_charts', 'etf_profile', 'get_etf_overview', 'helpers', 'iterate_live_quote', 'live_quote', 'load_chart', 'load_live_quote', 'load_overview', 'overview', 'types']
Help on function load_overview in module justetf_scraping.overview:

load_overview(strategy: Optional[Literal['epg-longOnly', 'epg-activeEtfs', 'epg-shortAndLeveraged']] = None, exchange: Optional[Literal['MUND', 'XETR', 'XLON', 'XPAR', 'XSTU', 'XSWX', 'XMIL', 'XAMS', 'XBRU', 'any']] = 'any', asset_class: Optional[Literal['class-equity', 'class-bonds', 'class-preciousMetals', 'class-commodities', 'class-currency', 'class-realEstate', 'class-moneyMarket']] = None, region: Optional[Literal['Africa', 'Asia%2BPacific', 'Eastern%2BEurope', 'Emerging%2BMarkets', 'Europe', 'Latin%2BAmerica', 'North%2BAmerica', 'World']] = None, country: str | None = None, instrument: Optional[Literal['ETC', 'ETF', 'ETN']] = None, provider: str | None = None, index_provider: str | None = None, index: str | None = None, isin: str | None = None, language: Literal['en', 'de', 'fr', 'it', 'es'] = 'en', local_country: Literal['DE', 'AT', 'CH', 'GB', 'IT', 'FR', 'ES', 'NL', 'BE'] = 'DE', universe: Literal['private', 'institutional'] = 'private', currency: Literal['EUR', 'USD', 'CHF', 'GBP'] = 'EUR', enrich: bool = False) -> pandas.DataFrame
    Load ETF overview data for the given parameters.

    Args
        strategy: Optional strategy query, see `STRATEGIES`. Strategies are
            disjunctive. If `None` (default), merge requests for all strategies.
        exchange: Optional exchange query, see `EXCHANGES`. If "any" (default),
            all exchanges are requested. If `None`, it seems that country
            specific exchanges are requested (e.g. gettex, XETRA and Stuttgart
            exchanges for DE).
        asset_class: Optional asset class query, see `ASSETS`. Assets are
            disjunctive. If `None` (default), all assets are requested.
        region: Optional region query, see `REGIONS`. Regions are currently
            disjunctive. If `None` (default), all regions are requested.
        country: Optional country query, represents the country targeted by the
            respective ETFs. Can be a country name or an alpha-2 code. If `None`
            (default), all target countries are selected.
        instrument: optional instrument query, see `INSTRUMENTS`. Instruments
            are disjunctive, If `None` (default), all instruments are requested.
        provider: Optional asset provider query.
        index_provider: Optional index provider query.
        index: Optional index query. Can be spotted in `qroupIndex` field in any
            response.
        isin: Optional ISIN query.
        language: Optional language for the response data, see `Language` for
            available options.
        local_country: Optional response country, see `Country` for available
            options.
        universe: Optional investor type, see `Universe` for available options.
        currency: Currency to get data in, see `Currency` for available options.
        enrich: Whether to enrich data with extra information. Currently, adds
            the following fields:
                `asset_class`: equity, bonds etc.
                `instrument`: ETC, ETF or ETN
                `region`: target region
                `exchange`: all exchanges the asset is available at.

In [3]:
import justetf_scraping.types as jtypes

for name in dir(jtypes):
    if not name.startswith("_"):
        val = getattr(jtypes, name)
        print(f"{name}: {val}")

AssetClass: typing.Literal['class-equity', 'class-bonds', 'class-preciousMetals', 'class-commodities', 'class-currency', 'class-realEstate', 'class-moneyMarket']
Country: typing.Literal['DE', 'AT', 'CH', 'GB', 'IT', 'FR', 'ES', 'NL', 'BE']
Currency: typing.Literal['EUR', 'USD', 'CHF', 'GBP']
Exchange: typing.Literal['MUND', 'XETR', 'XLON', 'XPAR', 'XSTU', 'XSWX', 'XMIL', 'XAMS', 'XBRU']
Instrument: typing.Literal['ETC', 'ETF', 'ETN']
Language: typing.Literal['en', 'de', 'fr', 'it', 'es']
Literal: typing.Literal
Quote: <class 'justetf_scraping.types.Quote'>
QuoteTrend: typing.Literal['down', 'up']
RawChart: <class 'justetf_scraping.types.RawChart'>
RawQuote: <class 'justetf_scraping.types.RawQuote'>
RawQuoteTrend: typing.Literal['I', 'D', 'U', 'N']
RawSeriesItem: <class 'justetf_scraping.types.RawSeriesItem'>
RawValue: <class 'justetf_scraping.types.RawValue'>
Region: typing.Literal['Africa', 'Asia%2BPacific', 'Eastern%2BEurope', 'Emerging%2BMarkets', 'Europe', 'Latin%2BAmerica', 'North%2BAmerica', 'World']
Strategy: typing.Literal['epg-longOnly', 'epg-activeEtfs', 'epg-shortAndLeveraged']
TypedDict: <function TypedDict at 0x000002B15D201300>
Universe: typing.Literal['private', 'institutional']
dataclasses: <module 'dataclasses' from 'C:\\Users\\navon\\anaconda3\\envs\\quant\\Lib\\dataclasses.py'>
datetime: <module 'datetime' from 'C:\\Users\\navon\\anaconda3\\envs\\quant\\Lib\\datetime.py'>
parse_quote: <function parse_quote at 0x000002B17A9ACEA0>
parse_quote_trend: <function parse_quote_trend at 0x000002B17A9ACE00>
warnings: <module 'warnings' from 'C:\\Users\\navon\\anaconda3\\envs\\quant\\Lib\\warnings.py'>

In [4]:
df_uk_equity = justetf_scraping.load_overview(
    exchange="XLON",
    asset_class="class-equity",
    instrument="ETF",
    local_country="GB",
    currency="GBP",
    enrich=True,
)

print(f"UK-listed equity ETFs: {len(df_uk_equity)}")
df_uk_equity[["ticker", "name", "inception_date", "age_in_years",
              "currency", "ter", "size"]].sort_values("size", ascending=False).head(30)

KeyboardInterrupt:

In [5]:
# fast: no enrichment, just the exchange/asset_class/instrument filter
df_uk_equity_raw = justetf_scraping.load_overview(
    exchange="XLON",
    asset_class="class-equity",
    instrument="ETF",
    local_country="GB",
    currency="GBP",
    enrich=False,
)
print(f"UK-listed equity ETFs (unenriched): {len(df_uk_equity_raw)}")
df_uk_equity_raw[["ticker", "name", "inception_date", "age_in_years", "currency", "ter", "size"]].head(10)

UK-listed equity ETFs (unenriched): 1597

,ticker,name,inception_date,age_in_years,currency,ter,size
isin,,,,,,,
IE00B5BMR087,CSP1,iShares Core S&P 500 UCITS ETF USD (Acc),2010-05-19,16.394521,USD,0.07,118149
IE00B4L5Y983,SWDA,iShares Core MSCI World UCITS ETF USD (Acc),2009-09-25,17.041096,USD,0.20,112120
IE00BK5BQT80,VWRP,Vanguard FTSE All-World UCITS ETF (USD) Accumu...,2019-07-23,7.210959,USD,0.14,46025
IE00B3XXRP09,VUSA,Vanguard S&P 500 UCITS ETF (USD) Distributing,2012-05-22,14.383562,USD,0.07,40335
IE00BKM4GZ66,EMIM,iShares Core MSCI Emerging Markets IMI UCITS E...,2014-05-30,12.361644,USD,0.18,34259
IE00B3YCGJ38,SPXP,Invesco S&P 500 UCITS ETF,2010-05-20,16.391781,USD,0.05,33239
IE00BFMXXD54,VUAG,Vanguard S&P 500 UCITS ETF (USD) Accumulating,2019-05-14,7.402740,USD,0.07,27832
IE00B6R52259,SSAC,iShares MSCI All Country World UCITS ETF USD (...,2011-10-21,14.969863,USD,0.20,27152
IE00B53SZB19,CNX1,iShares Nasdaq 100 UCITS ETF (Acc),2010-01-26,16.704110,USD,0.30,22491
IE00B3RBWM25,VWRL,Vanguard FTSE All-World UCITS ETF (USD) Distri...,2012-05-22,14.383562,USD,0.14,20452

In [6]:
tickers = df_uk_equity_raw["ticker"].dropna().unique().tolist()
print(f"Unique tickers to test: {len(tickers)}")

import yfinance as yf

full_tickers = [t + ".L" for t in tickers]

# batch download — much faster than looping per ticker
data = yf.download(full_tickers, period="5d", group_by="ticker",
                    auto_adjust=True, progress=True, threads=True)

print("Download shape:", data.shape)

Unique tickers to test: 1589

[*                      3%                       ]  52 of 1589 completed$FWDS.L: possibly delisted; no price data found  (period=5d)
[**                     4%                       ]  61 of 1589 completed$MWDP.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**                     4%                       ]  71 of 1589 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QRMW.L"}}}
[***                    6%                       ]  89 of 1589 completed$QRMW.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[***                    7%                       ]  112 of 1589 completed$XNZG.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[****                   8%                       ]  126 of 1589 completed$XEQ6.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*****                 10%                       ]  152 of 1589 completed$SX5D.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[********              17%                       ]  267 of 1589 completed$XEQ8.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[********              17%                       ]  274 of 1589 completed$OCTF.L: possibly delisted; no price data found  (period=5d)
[*********             18%                       ]  281 of 1589 completed$CECL.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*********             19%                       ]  301 of 1589 completed$EMRG.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[************          24%                       ]  378 of 1589 completed$XEQ2.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[***************       31%                       ]  495 of 1589 completed$WMSE.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[***************       32%                       ]  513 of 1589 completed$CSUKX.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[****************      33%                       ]  528 of 1589 completed$SUUE.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*****************     36%                       ]  577 of 1589 completed$CC1G.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[******************    37%                       ]  593 of 1589 completed$CSUKS.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[********************  41%                       ]  659 of 1589 completed$QUGB.L: possibly delisted; no price data found  (period=5d)
[**********************48%                       ]  762 of 1589 completed$TURL.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************48%                       ]  768 of 1589 completed$GQWX.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************48%                       ]  769 of 1589 completed$S3RA.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************51%                       ]  816 of 1589 completed$USAC.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************52%                       ]  821 of 1589 completed$SGQP.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************52%                       ]  828 of 1589 completed$XEQ4.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************56%**                     ]  894 of 1589 completed$EMUE.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************57%**                     ]  904 of 1589 completed$IM12.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************57%**                     ]  908 of 1589 completed$WSRI.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************57%**                     ]  911 of 1589 completed$XDND.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************60%****                   ]  961 of 1589 completed$USCO.L: possibly delisted; no price data found  (period=5d)
[**********************61%****                   ]  976 of 1589 completed$XBAS.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************64%******                 ]  1019 of 1589 completed$WMMV.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************65%******                 ]  1035 of 1589 completed$PAGB.L: possibly delisted; no price data found  (period=5d)
[**********************68%********               ]  1086 of 1589 completed$WMMS.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************69%********               ]  1099 of 1589 completed$WMFS.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************74%***********            ]  1168 of 1589 completed$CN1.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************76%***********            ]  1214 of 1589 completed$CHSI.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************80%*************          ]  1277 of 1589 completed$PQWP.L: possibly delisted; no price data found  (period=5d)
[**********************85%****************       ]  1351 of 1589 completed$CWEG.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************91%*******************    ]  1443 of 1589 completed$XDGM.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************95%*********************  ]  1511 of 1589 completed$MVEE.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  1584 of 1589 completed$JPNY.L: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  1589 of 1589 completed

40 Failed downloads:
['FWDS.L', 'OCTF.L', 'QUGB.L', 'USCO.L', 'PAGB.L', 'PQWP.L']: possibly delisted; no price data found  (period=5d)
['MWDP.L', 'QRMW.L', 'XNZG.L', 'XEQ6.L', 'SX5D.L', 'XEQ8.L', 'CECL.L', 'EMRG.L', 'XEQ2.L', 'WMSE.L', 'CSUKX.L', 'SUUE.L', 'CC1G.L', 'CSUKS.L', 'TURL.L', 'GQWX.L', 'S3RA.L', 'USAC.L', 'SGQP.L', 'XEQ4.L', 'EMUE.L', 'IM12.L', 'WSRI.L', 'XDND.L', 'XBAS.L', 'WMMV.L', 'WMMS.L', 'WMFS.L', 'CN1.L', 'CHSI.L', 'CWEG.L', 'XDGM.L', 'MVEE.L', 'JPNY.L']: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Download shape: (5, 7985)

In [7]:
failed = ['FWDS.L','OCTF.L','QUGB.L','USCO.L','PAGB.L','PQWP.L',
          'MWDP.L','QRMW.L','XNZG.L','XEQ6.L','SX5D.L','XEQ8.L','CECL.L',
          'EMRG.L','XEQ2.L','WMSE.L','CSUKX.L','SUUE.L','CC1G.L','CSUKS.L',
          'TURL.L','GQWX.L','S3RA.L','USAC.L','SGQP.L','XEQ4.L','EMUE.L',
          'IM12.L','WSRI.L','XDND.L','XBAS.L','WMMV.L','WMMS.L','WMFS.L',
          'CN1.L','CHSI.L','CWEG.L','XDGM.L','MVEE.L','JPNY.L']

good_tickers = [t for t in full_tickers if t not in failed]
print(f"Tickers to pull full history for: {len(good_tickers)}")

Tickers to pull full history for: 1549

In [8]:
import pandas as pd, yfinance as yf, time
from pathlib import Path

Path("data/processed").mkdir(parents=True, exist_ok=True)

CHUNK_SIZE = 50
all_prices = []
currency_map = {}
failed_tickers = []

for i in range(0, len(good_tickers), CHUNK_SIZE):
    chunk = good_tickers[i:i+CHUNK_SIZE]
    print(f"Batch {i//CHUNK_SIZE + 1}/{(len(good_tickers)-1)//CHUNK_SIZE + 1}  "
          f"({i}-{min(i+CHUNK_SIZE, len(good_tickers))} of {len(good_tickers)})")

    try:
        data = yf.download(chunk, period="max", group_by="ticker",
                            auto_adjust=True, progress=False, threads=True)
    except Exception as e:
        print(f"  batch error: {e}")
        failed_tickers.extend(chunk)
        continue

    for t in chunk:
        try:
            df_t = data[t].dropna(how="all")
            if df_t.empty:
                failed_tickers.append(t)
                continue
            df_t = df_t.reset_index()
            df_t["ticker"] = t.replace(".L", "")
            all_prices.append(df_t[["ticker","Date","Open","High","Low","Close","Volume"]])

            # currency check — needed for the GBX/pence fix
            try:
                currency_map[t.replace(".L","")] = yf.Ticker(t).fast_info.currency
            except Exception:
                currency_map[t.replace(".L","")] = "unknown"
        except Exception:
            failed_tickers.append(t)

    # periodic safety save every 10 batches (~500 tickers)
    if (i // CHUNK_SIZE) % 10 == 0 and all_prices:
        pd.concat(all_prices, ignore_index=True).to_csv(
            "data/processed/_prices_partial.csv", index=False)
        print(f"  [checkpoint saved: {len(all_prices)} tickers so far]")

print(f"\nDone. Succeeded: {len(all_prices)}  Failed: {len(failed_tickers)}")

Batch 1/31  (0-50 of 1549)
  [checkpoint saved: 50 tickers so far]
Batch 2/31  (50-100 of 1549)
Batch 3/31  (100-150 of 1549)
Batch 4/31  (150-200 of 1549)

EKGB.L: Period 'max' is invalid, must be one of: 1d, 5d

1 Failed download:
['EKGB.L']: Period 'max' is invalid, must be one of: 1d, 5d

Batch 5/31  (200-250 of 1549)
Batch 6/31  (250-300 of 1549)
Batch 7/31  (300-350 of 1549)
Batch 8/31  (350-400 of 1549)

$XPXJ.L: possibly delisted; no price data found  (period=5d)

Batch 9/31  (400-450 of 1549)
Batch 10/31  (450-500 of 1549)

$ASIL.L: possibly delisted; no price data found  (period=5d)

Batch 11/31  (500-550 of 1549)

$H50G.L: possibly delisted; no price data found  (period=5d)

  [checkpoint saved: 549 tickers so far]
Batch 12/31  (550-600 of 1549)
Batch 13/31  (600-650 of 1549)
Batch 14/31  (650-700 of 1549)

$INDA.L: possibly delisted; no price data found  (period=5d)
$CU2G.L: possibly delisted; no price data found  (period=5d)

Batch 15/31  (700-750 of 1549)

$SWWD.L: possibly delisted; no price data found  (period=5d)
$ACWL.L: possibly delisted; no price data found  (period=5d)
$XZSS.L: possibly delisted; no price data found  (period=5d)

Batch 16/31  (750-800 of 1549)

XIUS.L: Period 'max' is invalid, must be one of: 1d, 5d

1 Failed download:
['XIUS.L']: Period 'max' is invalid, must be one of: 1d, 5d
$FSUS.L: possibly delisted; no price data found  (period=5d)
$GOLB.L: possibly delisted; no price data found  (period=5d)

Batch 17/31  (800-850 of 1549)
Batch 18/31  (850-900 of 1549)

$MESR.L: possibly delisted; no price data found  (period=5d)

Batch 19/31  (900-950 of 1549)

$AWSR.L: possibly delisted; no price data found  (period=5d)
$UNCU.L: possibly delisted; no price data found  (period=5d)
$CM5S.L: possibly delisted; no price data found  (period=5d)

Batch 20/31  (950-1000 of 1549)

$XEMC.L: possibly delisted; no price data found  (period=5d)
$UC95.L: possibly delisted; no price data found  (period=5d)

Batch 21/31  (1000-1050 of 1549)

$PAWS.L: possibly delisted; no price data found  (period=5d)
$WWGB.L: possibly delisted; no price data found  (period=5d)
$RDVY.L: possibly delisted; no price data found  (period=5d)
$WIMG.L: possibly delisted; no price data found  (period=5d)
$XGLF.L: possibly delisted; no price data found  (period=5d)

  [checkpoint saved: 1048 tickers so far]
Batch 22/31  (1050-1100 of 1549)

XSWS.L: Period 'max' is invalid, must be one of: 1d, 5d

1 Failed download:
['XSWS.L']: Period 'max' is invalid, must be one of: 1d, 5d
$XCEU.L: possibly delisted; no price data found  (period=5d)
$XECT.L: possibly delisted; no price data found  (period=5d)
$EUFM.L: possibly delisted; no price data found  (period=5d)
$EDIV.L: possibly delisted; no price data found  (period=5d)
$MILL.L: possibly delisted; no price data found  (period=5d)
$CA3S.L: possibly delisted; no price data found  (period=5d)
$S5EQ.L: possibly delisted; no price data found  (period=5d)

Batch 23/31  (1100-1150 of 1549)

$XBUZ.L: possibly delisted; no price data found  (period=5d)
$PH0T.L: possibly delisted; no price data found  (period=5d)
$XZSW.L: possibly delisted; no price data found  (period=5d)
$WRLD.L: possibly delisted; no price data found  (period=5d)

Batch 24/31  (1150-1200 of 1549)

$HUKS.L: possibly delisted; no price data found  (period=5d)
$XCUU.L: possibly delisted; no price data found  (period=5d)
$XNNV.L: possibly delisted; no price data found  (period=5d)
$SPDA.L: possibly delisted; no price data found  (period=5d)
$VPAC.L: possibly delisted; no price data found  (period=5d)
$XUCA.L: possibly delisted; no price data found  (period=5d)
$CT5.L: possibly delisted; no price data found  (period=5d)
$XCJD.L: possibly delisted; no price data found  (period=5d)
$XG11.L: possibly delisted; no price data found  (period=5d)
$XUML.L: possibly delisted; no price data found  (period=5d)

Batch 25/31  (1200-1250 of 1549)

X5SP.L: Period 'max' is invalid, must be one of: 1d, 5d

1 Failed download:
['X5SP.L']: Period 'max' is invalid, must be one of: 1d, 5d
$5OGU.L: possibly delisted; no price data found  (period=5d)
$XNDX.L: possibly delisted; no price data found  (period=5d)
$GENG.L: possibly delisted; no price data found  (period=5d)
$WOMC.L: possibly delisted; no price data found  (period=5d)
$XDGS.L: possibly delisted; no price data found  (period=5d)
$UMC.L: possibly delisted; no price data found  (period=5d)
$FTES.L: possibly delisted; no price data found  (period=5d)
$EMGD.L: possibly delisted; no price data found  (period=5d)
$VRMD.L: possibly delisted; no price data found  (period=5d)
$SCTP.L: possibly delisted; no price data found  (period=5d)
$UXMC.L: possibly delisted; no price data found  (period=5d)

Batch 26/31  (1250-1300 of 1549)

FTSA.L: Period 'max' is invalid, must be one of: 1d, 5d
USOG.L: Period 'max' is invalid, must be one of: 1d, 5d
TCE.L: Period 'max' is invalid, must be one of: 1d, 5d

3 Failed downloads:
['FTSA.L', 'USOG.L', 'TCE.L']: Period 'max' is invalid, must be one of: 1d, 5d
$H2GB.L: possibly delisted; no price data found  (period=5d)
$USLP.L: possibly delisted; no price data found  (period=5d)
$FSCR.L: possibly delisted; no price data found  (period=5d)
$DVUS.L: possibly delisted; no price data found  (period=5d)
$KWBH.L: possibly delisted; no price data found  (period=5d)
$USAH.L: possibly delisted; no price data found  (period=5d)
$SPC3.L: possibly delisted; no price data found  (period=5d)
$EDVY.L: possibly delisted; no price data found  (period=5d)
$KWEH.L: possibly delisted; no price data found  (period=5d)
$CT5G.L: possibly delisted; no price data found  (period=5d)
$SDVI.L: possibly delisted; no price data found  (period=5d)
$LUNA.L: possibly delisted; no price data found  (period=5d)
$SAHP.L: possibly delisted; no price data found  (period=5d)
$TRE.L: possibly delisted; no price data found  (period=5d)
$FGRO.L: possibly delisted; no price data found  (period=5d)
$S5EW.L: possibly delisted; no price data found  (period=5d)
$HPUD.L: possibly delisted; no price data found  (period=5d)

Batch 27/31  (1300-1350 of 1549)

XEES.L: Period 'max' is invalid, must be one of: 1d, 5d

1 Failed download:
['XEES.L']: Period 'max' is invalid, must be one of: 1d, 5d
$JPCD.L: possibly delisted; no price data found  (period=5d)
$BLGB.L: possibly delisted; no price data found  (period=5d)
$UIGB.L: possibly delisted; no price data found  (period=5d)
$VRGD.L: possibly delisted; no price data found  (period=5d)
$BPGG.L: possibly delisted; no price data found  (period=5d)
$BPDG.L: possibly delisted; no price data found  (period=5d)

Batch 28/31  (1350-1400 of 1549)

JSME.L: Period 'max' is invalid, must be one of: 1d, 5d
XEEG.L: Period 'max' is invalid, must be one of: 1d, 5d
PQWX.L: Period 'max' is invalid, must be one of: 1d, 5d

3 Failed downloads:
['JSME.L', 'XEEG.L', 'PQWX.L']: Period 'max' is invalid, must be one of: 1d, 5d
$QREG.L: possibly delisted; no price data found  (period=5d)
$SAQL.L: possibly delisted; no price data found  (period=5d)
$QRSU.L: possibly delisted; no price data found  (period=5d)
$QRUE.L: possibly delisted; no price data found  (period=5d)

Batch 29/31  (1400-1450 of 1549)

$WOGH.L: possibly delisted; no price data found  (period=5d)
$JEAI.L: possibly delisted; no price data found  (period=5d)
$JUES.L: possibly delisted; no price data found  (period=5d)
$JUHG.L: possibly delisted; no price data found  (period=5d)
$3DEG.L: possibly delisted; no price data found  (period=5d)
$QGLO.L: possibly delisted; no price data found  (period=5d)

Batch 30/31  (1450-1500 of 1549)

CBSC.L: Period 'max' is invalid, must be one of: 1d, 5d
JGBT.L: Period 'max' is invalid, must be one of: 1d, 5d
PDWD.L: Period 'max' is invalid, must be one of: 1d, 5d

3 Failed downloads:
['CBSC.L', 'JGBT.L', 'PDWD.L']: Period 'max' is invalid, must be one of: 1d, 5d
$TEND.L: possibly delisted; no price data found  (period=5d)
$JESE.L: possibly delisted; no price data found  (period=5d)
$LEMV.L: possibly delisted; no price data found  (period=5d)
$TENM.L: possibly delisted; no price data found  (period=5d)
$GTIL.L: possibly delisted; no price data found  (period=5d)
$RDTG.L: possibly delisted; no price data found  (period=5d)
$GLRD.L: possibly delisted; no price data found  (period=5d)
$JADV.L: possibly delisted; no price data found  (period=5d)
$USEN.L: possibly delisted; no price data found  (period=5d)
$JSED.L: possibly delisted; no price data found  (period=5d)
$JXUS.L: possibly delisted; no price data found  (period=5d)
$HELA.L: possibly delisted; no price data found  (period=5d)
$RGSB.L: possibly delisted; no price data found  (period=5d)
$FGL1.L: possibly delisted; no price data found  (period=5d)
$JRDZ.L: possibly delisted; no price data found  (period=5d)
$JUNM.L: possibly delisted; no price data found  (period=5d)
$JRCD.L: possibly delisted; no price data found  (period=5d)
$HEDL.L: possibly delisted; no price data found  (period=5d)
$QRDG.L: possibly delisted; no price data found  (period=5d)
$JANF.L: possibly delisted; no price data found  (period=5d)

Batch 31/31  (1500-1549 of 1549)

PDWX.L: Period 'max' is invalid, must be one of: 1d, 5d

1 Failed download:
['PDWX.L']: Period 'max' is invalid, must be one of: 1d, 5d
$JULF.L: possibly delisted; no price data found  (period=5d)
$JSUD.L: possibly delisted; no price data found  (period=5d)
$JUDS.L: possibly delisted; no price data found  (period=5d)
$MDEC.L: possibly delisted; no price data found  (period=5d)
$SEPM.L: possibly delisted; no price data found  (period=5d)
$MARM.L: possibly delisted; no price data found  (period=5d)
$MARQ.L: possibly delisted; no price data found  (period=5d)
$QRED.L: possibly delisted; no price data found  (period=5d)
$JGDU.L: possibly delisted; no price data found  (period=5d)
$QRDU.L: possibly delisted; no price data found  (period=5d)
$JRXE.L: possibly delisted; no price data found  (period=5d)
$USGH.L: possibly delisted; no price data found  (period=5d)
$T3MD.L: possibly delisted; no price data found  (period=5d)
$JSUG.L: possibly delisted; no price data found  (period=5d)
$SPLU.L: possibly delisted; no price data found  (period=5d)

  [checkpoint saved: 1534 tickers so far]

Done. Succeeded: 1534  Failed: 15

In [9]:
# 1. Consolidate all price data collected so far
prices_df = pd.concat(all_prices, ignore_index=True)
prices_df.columns = ["ticker","date","open","high","low","close","volume"]
prices_df["date"] = pd.to_datetime(prices_df["date"])

actual_tickers_with_data = prices_df["ticker"].unique()
print(f"Tickers with real price data: {len(actual_tickers_with_data)}")
print(f"Total price rows: {len(prices_df):,}")
print(f"Date range: {prices_df['date'].min().date()} to {prices_df['date'].max().date()}")

# true failure list = requested minus what actually landed in prices_df
requested = [t.replace(".L","") for t in good_tickers]
truly_failed = sorted(set(requested) - set(actual_tickers_with_data))
print(f"Truly missing: {len(truly_failed)}")

Tickers with real price data: 1534
Total price rows: 2,707,129
Date range: 2008-01-02 to 2026-10-05
Truly missing: 15

In [10]:
# 2. Build metadata table: merge justETF fields + currency/scale fix
meta = df_uk_equity_raw.reset_index().rename(columns={"isin": "isin"})
meta["ticker_clean"] = meta["ticker"]
meta = meta[meta["ticker_clean"].isin(actual_tickers_with_data)].copy()

meta["currency_actual"] = meta["ticker_clean"].map(currency_map)
meta["price_scale"] = meta["currency_actual"].map({"GBp": 100, "GBP": 1, "USD": 1}).fillna(1)

meta_final = meta[["ticker_clean","isin","name","inception_date","age_in_years",
                    "currency","currency_actual","price_scale","ter","size"]]
meta_final = meta_final.rename(columns={"ticker_clean": "ticker",
                                         "currency": "base_currency",
                                         "currency_actual": "quote_currency"})
print(f"Metadata rows: {len(meta_final)}")
meta_final.head(10)

Metadata rows: 1535

,ticker,isin,name,inception_date,age_in_years,base_currency,quote_currency,price_scale,ter,size
0,CSP1,IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD (Acc),2010-05-19,16.394521,USD,GBp,100.0,0.07,118149
1,SWDA,IE00B4L5Y983,iShares Core MSCI World UCITS ETF USD (Acc),2009-09-25,17.041096,USD,GBp,100.0,0.20,112120
2,VWRP,IE00BK5BQT80,Vanguard FTSE All-World UCITS ETF (USD) Accumu...,2019-07-23,7.210959,USD,GBP,1.0,0.14,46025
3,VUSA,IE00B3XXRP09,Vanguard S&P 500 UCITS ETF (USD) Distributing,2012-05-22,14.383562,USD,GBP,1.0,0.07,40335
4,EMIM,IE00BKM4GZ66,iShares Core MSCI Emerging Markets IMI UCITS E...,2014-05-30,12.361644,USD,GBp,100.0,0.18,34259
5,SPXP,IE00B3YCGJ38,Invesco S&P 500 UCITS ETF,2010-05-20,16.391781,USD,GBp,100.0,0.05,33239
6,VUAG,IE00BFMXXD54,Vanguard S&P 500 UCITS ETF (USD) Accumulating,2019-05-14,7.402740,USD,GBP,1.0,0.07,27832
7,SSAC,IE00B6R52259,iShares MSCI All Country World UCITS ETF USD (...,2011-10-21,14.969863,USD,GBp,100.0,0.20,27152
8,CNX1,IE00B53SZB19,iShares Nasdaq 100 UCITS ETF (Acc),2010-01-26,16.704110,USD,GBp,100.0,0.30,22491
9,VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF (USD) Distri...,2012-05-22,14.383562,USD,GBP,1.0,0.14,20452

In [11]:
# 3. Write both CSVs
prices_df.sort_values(["ticker","date"]).to_csv(
    "data/processed/uk_etf_prices.csv", index=False)
meta_final.to_csv("data/processed/uk_etf_metadata.csv", index=False)

import os
print("prices.csv size:", round(os.path.getsize("data/processed/uk_etf_prices.csv")/1e6, 1), "MB")
print("metadata.csv size:", round(os.path.getsize("data/processed/uk_etf_metadata.csv")/1e6, 2), "MB")

prices.csv size: 225.0 MB
metadata.csv size: 0.19 MB

In [12]:
# 1. Dedupe metadata — keep the first occurrence per ticker
dupe_count = meta_final["ticker"].duplicated().sum()
print(f"Duplicate ticker rows found: {dupe_count}")
meta_final = meta_final.drop_duplicates(subset="ticker", keep="first").reset_index(drop=True)
print(f"Metadata rows after dedupe: {len(meta_final)}")

# 2. Normalize prices to GBP — apply price_scale (100 for GBX/pence, 1 for GBP/USD)
scale_map = meta_final.set_index("ticker")["price_scale"].to_dict()
prices_df["scale"] = prices_df["ticker"].map(scale_map).fillna(1)

for col in ["open", "high", "low", "close"]:
    prices_df[col] = prices_df[col] / prices_df["scale"]

prices_df = prices_df.drop(columns="scale")

# sanity check: no more 100x jumps between similar funds
print(prices_df.groupby("ticker")["close"].last().describe())

Duplicate ticker rows found: 1
Metadata rows after dedupe: 1534
count     1534.000000
mean       119.090142
std       1205.359228
min          0.047020
25%         10.514250
50%         24.537500
75%         54.603750
max      37570.000000
Name: close, dtype: float64

In [13]:
# 3. Re-save final, corrected files
prices_df.sort_values(["ticker","date"]).to_csv(
    "data/processed/uk_etf_prices.csv", index=False)
meta_final.to_csv("data/processed/uk_etf_metadata.csv", index=False)

import os
Path("data/processed/_prices_partial.csv").unlink(missing_ok=True)  # cleanup checkpoint
print("prices.csv:", round(os.path.getsize("data/processed/uk_etf_prices.csv")/1e6, 1), "MB")
print("metadata.csv:", round(os.path.getsize("data/processed/uk_etf_metadata.csv")/1e6, 2), "MB")
print("Done — downstream notebooks now just pd.read_csv() these two files.")

prices.csv: 223.1 MB
metadata.csv: 0.19 MB
Done — downstream notebooks now just pd.read_csv() these two files.

In [14]:
unknown_currency = meta_final[meta_final["quote_currency"] == "unknown"]
print(f"Tickers with unresolved currency: {len(unknown_currency)}")
unknown_currency[["ticker","name","base_currency","quote_currency"]]

Tickers with unresolved currency: 121

,ticker,name,base_currency,quote_currency
365,XPXJ,Xtrackers MSCI Pacific ex Japan UCITS ETF 1C,USD,unknown
497,ASIL,Amundi MSCI China ESG Selection Extra UCITS ET...,EUR,unknown
512,H50G,HSBC Euro Stoxx 50 UCITS ETF GBP Hedged (Acc),GBP,unknown
657,INDA,UBS MSCI India SF UCITS ETF USD (Acc),USD,unknown
664,CU2G,Amundi PEA MSCI USA ESG Selection UCITS ETF USD,USD,unknown
...,...,...,...,...
1507,JRXE,JPMorgan AC Asia Pacific ex Japan Research Enh...,USD,unknown
1509,USGH,iShares US Equity Enhanced Active UCITS ETF GB...,GBP,unknown
1511,T3MD,JPMorgan Climate Change Solutions Active UCITS...,USD,unknown
1520,JSUG,JPMorgan US Research Enhanced Index Equity SRI...,GBP,unknown
1521,SPLU,PIMCO Advantage StocksPLUS US Large Cap UCITS ...,USD,unknown

In [15]:
# flag any suspiciously high closes — likely un-scaled GBX funds
latest_close = prices_df.groupby("ticker")["close"].last().sort_values(ascending=False)
print(latest_close.head(15))

ticker
ACWL    37570.000000
LEMV    25595.000000
ASIL     8367.500000
XPXJ     6996.000000
LCJP     4331.410156
IUQD     2698.000000
JULF     2223.750000
JSUG     2140.250000
LUNA     1501.300049
CNX1     1338.300000
CAPU     1240.550000
S5EQ      891.750000
S5EW      863.150024
XLKQ      854.100000
CT5       747.099976
Name: close, dtype: float64

In [16]:
import time

retry_currency = {}
still_unknown = []

for t in unknown_currency["ticker"].tolist():
    try:
        c = yf.Ticker(t + ".L").fast_info.currency
        retry_currency[t] = c if c else "unknown"
    except Exception:
        still_unknown.append(t)
    time.sleep(0.3)  # small delay — likely rate-limiting caused the original failures

print(f"Resolved on retry: {sum(1 for v in retry_currency.values() if v != 'unknown')}")
print(f"Still unresolved: {len(still_unknown) + sum(1 for v in retry_currency.values() if v == 'unknown')}")
pd.Series(retry_currency).value_counts()

$XPXJ.L: possibly delisted; no price data found  (period=5d)
$ASIL.L: possibly delisted; no price data found  (period=5d)
$H50G.L: possibly delisted; no price data found  (period=5d)
$INDA.L: possibly delisted; no price data found  (period=5d)
$CU2G.L: possibly delisted; no price data found  (period=5d)
$SWWD.L: possibly delisted; no price data found  (period=5d)
$ACWL.L: possibly delisted; no price data found  (period=5d)
$XZSS.L: possibly delisted; no price data found  (period=5d)
$FSUS.L: possibly delisted; no price data found  (period=5d)
$GOLB.L: possibly delisted; no price data found  (period=5d)
$MESR.L: possibly delisted; no price data found  (period=5d)
$AWSR.L: possibly delisted; no price data found  (period=5d)
$UNCU.L: possibly delisted; no price data found  (period=5d)
$CM5S.L: possibly delisted; no price data found  (period=5d)
$XEMC.L: possibly delisted; no price data found  (period=5d)
$UC95.L: possibly delisted; no price data found  (period=5d)
$PAWS.L: possibly delisted; no price data found  (period=5d)
$WWGB.L: possibly delisted; no price data found  (period=5d)
$RDVY.L: possibly delisted; no price data found  (period=5d)
$WIMG.L: possibly delisted; no price data found  (period=5d)
$XGLF.L: possibly delisted; no price data found  (period=5d)
$XCEU.L: possibly delisted; no price data found  (period=5d)
$XECT.L: possibly delisted; no price data found  (period=5d)
$EUFM.L: possibly delisted; no price data found  (period=5d)
$EDIV.L: possibly delisted; no price data found  (period=5d)
$MILL.L: possibly delisted; no price data found  (period=5d)
$CA3S.L: possibly delisted; no price data found  (period=5d)
$S5EQ.L: possibly delisted; no price data found  (period=5d)
$XBUZ.L: possibly delisted; no price data found  (period=5d)
$PH0T.L: possibly delisted; no price data found  (period=5d)
$XZSW.L: possibly delisted; no price data found  (period=5d)
$WRLD.L: possibly delisted; no price data found  (period=5d)
$HUKS.L: possibly delisted; no price data found  (period=5d)
$XCUU.L: possibly delisted; no price data found  (period=5d)
$XNNV.L: possibly delisted; no price data found  (period=5d)
$SPDA.L: possibly delisted; no price data found  (period=5d)
$VPAC.L: possibly delisted; no price data found  (period=5d)
$XUCA.L: possibly delisted; no price data found  (period=5d)
$CT5.L: possibly delisted; no price data found  (period=5d)
$XCJD.L: possibly delisted; no price data found  (period=5d)
$XG11.L: possibly delisted; no price data found  (period=5d)
$XUML.L: possibly delisted; no price data found  (period=5d)
$5OGU.L: possibly delisted; no price data found  (period=5d)
$XNDX.L: possibly delisted; no price data found  (period=5d)
$GENG.L: possibly delisted; no price data found  (period=5d)
$WOMC.L: possibly delisted; no price data found  (period=5d)
$XDGS.L: possibly delisted; no price data found  (period=5d)
$UMC.L: possibly delisted; no price data found  (period=5d)
$FTES.L: possibly delisted; no price data found  (period=5d)
$EMGD.L: possibly delisted; no price data found  (period=5d)
$VRMD.L: possibly delisted; no price data found  (period=5d)
$SCTP.L: possibly delisted; no price data found  (period=5d)
$UXMC.L: possibly delisted; no price data found  (period=5d)
$H2GB.L: possibly delisted; no price data found  (period=5d)
$USLP.L: possibly delisted; no price data found  (period=5d)
$FSCR.L: possibly delisted; no price data found  (period=5d)
$DVUS.L: possibly delisted; no price data found  (period=5d)
$KWBH.L: possibly delisted; no price data found  (period=5d)
$USAH.L: possibly delisted; no price data found  (period=5d)
$SPC3.L: possibly delisted; no price data found  (period=5d)
$EDVY.L: possibly delisted; no price data found  (period=5d)
$KWEH.L: possibly delisted; no price data found  (period=5d)
$CT5G.L: possibly delisted; no price data found  (period=5d)
$SDVI.L: possibly delisted; no price data found  (period=5d)
$LUNA.L: possibly delisted; no price data found  (period=5d)
$SAHP.L: possibly delisted; no price data found  (period=5d)
$TRE.L: possibly delisted; no price data found  (period=5d)
$FGRO.L: possibly delisted; no price data found  (period=5d)
$S5EW.L: possibly delisted; no price data found  (period=5d)
$HPUD.L: possibly delisted; no price data found  (period=5d)
$JPCD.L: possibly delisted; no price data found  (period=5d)
$BLGB.L: possibly delisted; no price data found  (period=5d)
$UIGB.L: possibly delisted; no price data found  (period=5d)
$VRGD.L: possibly delisted; no price data found  (period=5d)
$BPGG.L: possibly delisted; no price data found  (period=5d)
$BPDG.L: possibly delisted; no price data found  (period=5d)
$QREG.L: possibly delisted; no price data found  (period=5d)
$SAQL.L: possibly delisted; no price data found  (period=5d)
$QRSU.L: possibly delisted; no price data found  (period=5d)
$QRUE.L: possibly delisted; no price data found  (period=5d)
$WOGH.L: possibly delisted; no price data found  (period=5d)
$JEAI.L: possibly delisted; no price data found  (period=5d)
$JUES.L: possibly delisted; no price data found  (period=5d)
$JUHG.L: possibly delisted; no price data found  (period=5d)
$3DEG.L: possibly delisted; no price data found  (period=5d)
$QGLO.L: possibly delisted; no price data found  (period=5d)
$TEND.L: possibly delisted; no price data found  (period=5d)
$JESE.L: possibly delisted; no price data found  (period=5d)
$LEMV.L: possibly delisted; no price data found  (period=5d)
$TENM.L: possibly delisted; no price data found  (period=5d)
$GTIL.L: possibly delisted; no price data found  (period=5d)
$RDTG.L: possibly delisted; no price data found  (period=5d)
$GLRD.L: possibly delisted; no price data found  (period=5d)
$JADV.L: possibly delisted; no price data found  (period=5d)
$USEN.L: possibly delisted; no price data found  (period=5d)
$JSED.L: possibly delisted; no price data found  (period=5d)
$JXUS.L: possibly delisted; no price data found  (period=5d)
$HELA.L: possibly delisted; no price data found  (period=5d)
$RGSB.L: possibly delisted; no price data found  (period=5d)
$FGL1.L: possibly delisted; no price data found  (period=5d)
$JRDZ.L: possibly delisted; no price data found  (period=5d)
$JUNM.L: possibly delisted; no price data found  (period=5d)
$JRCD.L: possibly delisted; no price data found  (period=5d)
$HEDL.L: possibly delisted; no price data found  (period=5d)
$QRDG.L: possibly delisted; no price data found  (period=5d)
$JANF.L: possibly delisted; no price data found  (period=5d)
$JULF.L: possibly delisted; no price data found  (period=5d)
$JSUD.L: possibly delisted; no price data found  (period=5d)
$JUDS.L: possibly delisted; no price data found  (period=5d)
$MDEC.L: possibly delisted; no price data found  (period=5d)
$SEPM.L: possibly delisted; no price data found  (period=5d)
$MARM.L: possibly delisted; no price data found  (period=5d)
$MARQ.L: possibly delisted; no price data found  (period=5d)
$QRED.L: possibly delisted; no price data found  (period=5d)
$JGDU.L: possibly delisted; no price data found  (period=5d)
$QRDU.L: possibly delisted; no price data found  (period=5d)
$JRXE.L: possibly delisted; no price data found  (period=5d)
$USGH.L: possibly delisted; no price data found  (period=5d)
$T3MD.L: possibly delisted; no price data found  (period=5d)
$JSUG.L: possibly delisted; no price data found  (period=5d)
$SPLU.L: possibly delisted; no price data found  (period=5d)

Resolved on retry: 0
Still unresolved: 121

Series([], Name: count, dtype: int64)

In [17]:
# apply the newly-resolved currencies: rescale only rows that turned out GBp
new_scale = {t: (100 if c == "GBp" else 1) for t, c in retry_currency.items()}

affected = [t for t, s in new_scale.items() if s == 100]
print(f"Tickers needing rescale (GBX->GBP): {len(affected)}")

mask = prices_df["ticker"].isin(affected)
for col in ["open", "high", "low", "close"]:
    prices_df.loc[mask, col] = prices_df.loc[mask, col] / 100

# update metadata with resolved currencies
meta_final["quote_currency"] = meta_final.apply(
    lambda r: retry_currency.get(r["ticker"], r["quote_currency"]), axis=1)
meta_final["price_scale"] = meta_final.apply(
    lambda r: new_scale.get(r["ticker"], r["price_scale"]), axis=1)

# re-check the outlier closes
latest_close = prices_df.groupby("ticker")["close"].last().sort_values(ascending=False)
print(latest_close.head(15))
print(f"\nStill-unknown tickers remaining: {(meta_final['quote_currency']=='unknown').sum()}")

Tickers needing rescale (GBX->GBP): 0
ticker
ACWL    37570.000000
LEMV    25595.000000
ASIL     8367.500000
XPXJ     6996.000000
LCJP     4331.410156
IUQD     2698.000000
JULF     2223.750000
JSUG     2140.250000
LUNA     1501.300049
CNX1     1338.300000
CAPU     1240.550000
S5EQ      891.750000
S5EW      863.150024
XLKQ      854.100000
CT5       747.099976
Name: close, dtype: float64

Still-unknown tickers remaining: 121

In [18]:
unresolved_tickers = meta_final.loc[meta_final["quote_currency"]=="unknown", "ticker"].tolist()

last_close = prices_df[prices_df["ticker"].isin(unresolved_tickers)].groupby("ticker")["close"].last()

THRESHOLD = 1000  # GBP-quoted ETF units essentially never exceed this
inferred_scale = last_close.apply(lambda x: 100 if x > THRESHOLD else 1)

print(f"Inferred as GBX (pence) -> rescale: {(inferred_scale == 100).sum()}")
print(f"Inferred as already GBP: {(inferred_scale == 1).sum()}")
inferred_scale.sort_values(ascending=False).head(20)

Inferred as GBX (pence) -> rescale: 7
Inferred as already GBP: 114

ticker
ACWL    100
ASIL    100
LUNA    100
LEMV    100
JULF    100
JSUG    100
XPXJ    100
5OGU      1
3DEG      1
CM5S      1
CT5       1
CT5G      1
CU2G      1
DVUS      1
EDIV      1
EDVY      1
EMGD      1
EUFM      1
FGL1      1
FGRO      1
Name: close, dtype: int64

In [19]:
affected = inferred_scale[inferred_scale == 100].index.tolist()
mask = prices_df["ticker"].isin(affected)
for col in ["open","high","low","close"]:
    prices_df.loc[mask, col] = prices_df.loc[mask, col] / 100

meta_final["price_scale"] = meta_final.apply(
    lambda r: inferred_scale.get(r["ticker"], r["price_scale"]), axis=1)
meta_final["quote_currency"] = meta_final.apply(
    lambda r: ("GBp (inferred)" if inferred_scale.get(r["ticker"]) == 100
               else "GBP (inferred)") if r["ticker"] in unresolved_tickers
               else r["quote_currency"], axis=1)

# re-save final files
prices_df.sort_values(["ticker","date"]).to_csv("data/processed/uk_etf_prices.csv", index=False)
meta_final.to_csv("data/processed/uk_etf_metadata.csv", index=False)

latest_close_final = prices_df.groupby("ticker")["close"].last().sort_values(ascending=False)
print(latest_close_final.head(10))
print(f"\nMax close now: {latest_close_final.max():.2f}")

ticker
LCJP    4331.410156
IUQD    2698.000000
CNX1    1338.300000
CAPU    1240.550000
S5EQ     891.750000
S5EW     863.150024
XLKQ     854.100000
CT5      747.099976
UC67     745.799988
CU2G     732.200012
Name: close, dtype: float64

Max close now: 4331.41